### ISSUE TITLE
Mock dataset

### ISSUE THREAD

**Issue by Tims777** [amosproj/amos2023ws06-sales-lead-qualifier#115]
We want to be able to present our Mid-Project Release without the risk of leaking sensitive data.
Therefore we need a mock dataset, that can be used to demo our project state.

Data Fields:
* First & Last Name
* Email 
* Phone Number
* Company Name

### Acceptance Criteria
* The file should contain at least 10 entries.
* The mock dataset works in place of our real dataset.
* The mock dataset is realistic in terms of result quality.

**Comment by felix-zailskas** [comment]
Csv file has been uploaded to S3 and can be found under
`s3://amos--data--events/demo/demo_leads.csv`

**Comment by felix-zailskas** [comment]
Names are not always accurate but also not used in our pipeline so that should not affect the demo

**Comment by ur-tech** [comment]
- Column names correct
- Correct data (except few person names)
- Variety of origin
- Also checked the dataset with our pipeline using our dev:
- correct: wanke, mathieu, kabbir, djampour, zuse (5)
- problem: uhe (multiple company branches) => use specific phonenumber
- wrong: zehender, van Toor (solveable by using phonenumber), and Lauser (solveable by website)

Good choice of the companies origin (most common countries are included) and the data is correct (except for very few persons names). It will be also interesting to see, how our pipeline handles the "Uhe,Erika,Centimeter,+4314700606,info@centimeter.at" because it is a company with multiple branches in Vienna

Regarding the Acceptanve criteria:
- [ ] The file should contain at least 10 entries.
- [ ] The mock dataset works in place of our real dataset.
- [ ] The mock dataset is realistic in terms of result quality.
