### ISSUE TITLE
Research: Business type analysis

### ISSUE THREAD

**Issue by Tims777** [amosproj/amos2023ws06-sales-lead-qualifier#195]
Using GPT for the business type analysis is possible but quite expensive. Instead we could opt for more conventional (e.g. keyword-based) analysis or we can use an open LLM (https://github.com/eugeneyan/open-llms).

### Acceptance Criteria
* Business type analysis (based on already collected data)
  * has been documented and / or implemented

**Comment by ruchita-nathani** [comment]
I found an open-source LLM model on Hugging Face at  https://huggingface.co/LLM360/CrystalChat
However, it's computationally heavy and can't be run on our local machine. I ran it on colab, but there's also a GPU limitation. 
Thus, I suggest that we use OpenAI instead of looking for an open LLM model. 
Running an open LLM model on our machine will significantly increase infrastructure costs. I'll discuss this with the team.
