### ISSUE TITLE
Agree with industry partner on scope of project & system design

### ISSUE THREAD

**Issue by Tims777** [amosproj/amos2023ws06-sales-lead-qualifier#4]

**Comment by luccalb** [comment]
Here are some questions to discuss with Andi and in the Team:

- Shoud all collected data be reduced into a single "expected value" or would the sales team also be interested in (some of) the source data we use for prediction?
- What data is included in the historical data we'll receive from SumUp? What data do we want to collect additionaly? If we want to train an AI on historical data, afaik we have to collect the same features, that were given in the train datastet, for every lead to generate a prediction. (This is a question for the AI experts)
- How can we integrate best with existing SumUp Infrastructure? Can we receive lead data directly through e.g. a webhook? Can we write our output data directly into a CRM instead of a Google Doc?

**Comment by luccalb** [comment]
I've also created example component and sequence diagrams (these are **not meant to be final versions**, but rather a starting point for discussion).

The draw.io file can be found in our shared drive, **feel free to add your ideas**:
https://drive.google.com/file/d/1rlwwPdPz573pDCIimEPmvs-y1f8uwY6H/view?usp=sharing

![Image](https://github.com/amosproj/amos2023ws06-sales-lead-qualifier/assets/44930425/ca2b9bf9-1e32-441d-b79e-fd12851cc1d3)
![Image](https://github.com/amosproj/amos2023ws06-sales-lead-qualifier/assets/44930425/d49fc208-31e2-43ac-a57f-a15e664e5fdb)

**Comment by NicoHambauer** [comment]
Hey Lucca,
looks solid! Nice job!! :)

**Comment by NicoHambauer** [comment]
> Here are some questions to discuss with Andi and in the Team:
> 
> * Shoud all collected data be reduced into a single "expected value" or would the sales team also be interested in (some of) the source data we use for prediction?
> * What data is included in the historical data we'll receive from SumUp? What data do we want to collect additionaly? If we want to train an AI on historical data, afaik we have to collect the same features, that were given in the train datastet, for every lead to generate a prediction. (This is a question for the AI experts)
> * How can we integrate best with existing SumUp Infrastructure? Can we receive lead data directly through e.g. a webhook? Can we write our output data directly into a CRM instead of a Google Doc?

Hey Lucca, happy to see some questions already formulated.
You can reformulated them using the new information of our enhanced project description and maybe you find more questions.
I encourage you and everyone to send those to Andi via our joint slack channel sumup-external.
