### ISSUE TITLE
Aggregate actual data

### ISSUE THREAD

**Issue by Tims777** [amosproj/amos2023ws06-sales-lead-qualifier#50]
Our industry partner pointed out how important it is, to get started with collecting (at least some) data from external data sources as soon as possible. This way we can progress more quickly with the EVP and just as important can we provide our industry partner with first valuable data.

### Verifying
TODO: Add common instructions for verifying.

### Implementation Notes
Try to keep number API calls low! E.g. try not to re-run the same queries too often. Experiment with small datasets.

### Done?
* Verify collected data for at least 20 leads.
* Have at least one additional external data sources set up.
* Document what data is available from that source.
* Demonstrate functionality by retrieving some actually valuable data for at least some leads.
* At least one unit test case per data source.

**Comment by luccalb** [comment]
In #51 we added the results of our mob programming session on thursday:

- Basic Pipeline/Step Framework to build on
- Data Enrichment / Manipulation through pandas dataframes
- Parsing Emails for custom domains
- Parsing those websites for physical business addresses
- Searching for the domains in Google Places and storing `formatted_address`, `user_ratings_no`, `business_status` and `name`
- Added some test cases for the pipeline and API usage limits

**Comment by soapyheas** [comment]
I'll be experimenting with GPT as a data source using our new framework this week.

**Comment by ur-tech** [comment]
1. I will integrate the phone number features as a step into the pipeline
2. I thought because of my study background (and around 70% of the companies are german), I will focus on this data source: https://github.com/bundesAPI/deutschland. To get financial information like Handelsregister/Bundesanzeiger and also demographical features (age distribution in a region, etc.)

**Comment by luccalb** [comment]
Additional potential data sources:

- Social Media
  - X
  - TikTok
  - Instagram
  - Facebook
- Detailed website parsing (e.g. Imprint/Impressum)
- Checking commercial email accounts (e.g. `<business.name>@gmail.com`), which are currently ignored

@Tims777 i think it makes sense to convert the bulletpoints to draft issues so we can keep track of all the ideas

**Comment by Tims777** [comment]
> @Tims777 i think it makes sense to convert the bulletpoints to draft issues so we can keep track of all the ideas

Good idea!

**Comment by rbbozkurt** [comment]
**1. openAI APIs (GPT)**

**- GPT-3**
 - **Overview**: he GPT-3 API is the most widely known and used. It offers access to the powerful language model, GPT-3, which can generate text, answer questions, summarize content, and more. The API provides various endpoints for different tasks, including completion, search, and conversation.
  - **Features**: Customizable prompts, adjustable parameters for response control (like temperature and max tokens), and a choice of different models under the GPT-3 umbrella.
  - **Usage Limits**: The API has usage limits based on the subscription plan. OpenAI offers both free and paid plans with varying levels of access and usage limits.
 - **Python Integration**: OpenAI provides an official Python client library for the GPT-3 API. This library simplifies authentication, request making, and response handling. It's well-documented and easy to use.

**- Fine-Tuning GPT-3 API**
  - **Overview**: OpenAI also offers the capability to fine-tune GPT-3 models. This allows developers to train the model on specific datasets to better suit their unique use cases.
  - **Python Integration**: The fine-tuning process can be managed using the same Python client library as the standard GPT-3 API.
 
**- GPT-4 API**
- **Overview**: The GPT-4 API extends the functionalities of GPT-3, offering more advanced capabilities, a larger context window, and improved response accuracy.
- **Access**: Initially, access to the GPT-4 API was limited to ChatGPT Plus subscribers, but it has been gradually opening up for wider usage.
- **Python Integration**: The integration method is similar to GPT-3, using the same Python client library provided by OpenAI.


**- General Points for OpenAI's GPT APIs**
  - **Authentication**: Access to these APIs requires an API key provided by OpenAI. This key is used for authenticating requests.
  - **Documentation and Support:** OpenAI provides comprehensive documentation, including guides on how to use the APIs with Python.
  -  **Compliance and Guidelines**: Users of the API must comply with OpenAI's use-case policies and guidelines.


**2. Social Media APIs**

**- Instagram API**
-  **Official API**: Instagram Graph API allows for managing media objects, reading data, and performing actions on behalf of Instagram Business Accounts. However, it has limitations for personal accounts.
- **Python Integration**: There are Python libraries like `instagram_private_api` for personal accounts, but they are unofficial and may have limitations or risks.

**- TikTok API**
- **Official API**: TikTok has an official API for accessing and managing content, user interactions, and more. It's mainly geared towards businesses and developers creating marketing and analytics tools.
- **Python Integration:** Python libraries such as `TikTokApi` provide a way to interact with TikTok data. Note that these libraries often face challenges due to frequent changes in TikTok's internal API.
   
**- Facebook API**

 - **Official API**: The Facebook Graph API allows access to data on Facebook, including user profiles, groups, posts, and more. It's a comprehensive API with extensive documentation.
 - **Python Integration**: Python's `facebook-sdk` library is a popular choice for interacting with the Facebook Graph API.


**- Twitter (X) API**
 - **Official API**: Twitter offers an API for accessing tweets, user profiles, sending tweets, and more. The API is well-documented and widely used.
 - **Python Integration**: Libraries like `tweepy` make it easy to interact with the Twitter API using Python. It provides methods for most Twitter API endpoints.

**- General Points for Social Media APIs**
- Each of these APIs requires proper authentication, typically using OAuth, and adheres to specific usage limits and guidelines set by the respective platforms. Developers need to register their applications with the platform to get the necessary credentials for API access. 
-  Additionally, due to the changing nature of these APIs, it's important to stay updated with the latest documentation and terms of use.

**Comment by soapyheas** [comment]
As specified in the meeting summary from 13/11/23, Andi shared the following ideas:

> I would first go wide!! After we have the:
> - Density in the area
> - sum up customers in the area
> - how much rev. did they generate

From the Google Places API framework, we can also retrieve the coordinates of the company. The "Nearby Search" API, also from Google can be used to find information on surrounding companies:
https://developers.google.com/maps/documentation/places/web-service/search-nearby

**Comment by ultiwinter** [comment]
**_Facebook Graph API:_** After implementing Facebook Graph API on branch feature/social-media-api, unfortunately, Facebook Graph API does not allow getting the users' id, which is required to get more info about the user. The access to this functionality has been limited and restricted in many cases.
**_Instagram API:_** instagram_private_api API is not officially supported by Instagram and using it violates Instagram's terms of service.

**Comment by soapyheas** [comment]
**_GPT3 API:_** GPT3 basic structure implemented (yet to be pushed), however there have been many problems with experimenting with the free API. Max RPM is 3, and max RPD is 200. Further, the amount of free credits is only $18. It would be worth asking SumUp for the GPT API key (if they have one).

**_Bing Search API:_** I found that GPT wasn't helpful with providing additional data on companies we have extracted using the Google API. However, I thought about using its ability to synthesise information. In a way to mimic the Bing GPT search extension (which doesn't have an API), we could use the Bing Search API to retrieve online information from social media etc, then feed the results into GPT. However, I also had trouble with accessing the Bing Search API free trial to experiment with this.

**Comment by Tims777** [comment]
Closing this at "not planned" since the definition of done was partially incomplete and deviates from what was actually required.
For the record: Parts of this have indeed been completed already. Other parts are now being tracked by the following items:
* #71 
* #73 
* #74 
* #75 
* #76 
* #77 
* #78
